# Generated by Django 3.2.14 on 2022-07-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeframework',
            name='home_framework_text',
        ),
    ]
