# Generated by Django 3.2.5 on 2022-06-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menus',
            new_name='Menu',
        ),
    ]
