# Generated by Django 3.2.14 on 2022-08-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0002_remove_homeframework_home_framework_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeFramework',
        ),
        migrations.AddField(
            model_name='stage',
            name='home_stage_image',
            field=models.ImageField(blank=True, upload_to='home_stage_image'),
        ),
    ]
