# Generated by Django 3.2.5 on 2022-06-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0002_rename_menus_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='HomeMenu',
        ),
    ]
