# Generated by Django 3.2.5 on 2022-06-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0003_rename_menu_homemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(max_length=200, upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='HeaderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(max_length=200, upload_to='')),
                ('info_image', models.ImageField(max_length=200, upload_to='')),
                ('education_image', models.ImageField(max_length=200, upload_to='')),
                ('research_image', models.ImageField(max_length=200, upload_to='')),
                ('innovation_image', models.ImageField(max_length=200, upload_to='')),
                ('mission_image', models.ImageField(max_length=200, upload_to='')),
                ('policies_image', models.ImageField(max_length=200, upload_to='')),
                ('plans_image', models.ImageField(max_length=200, upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameModel(
            old_name='HomeMenu',
            new_name='FooterMenu',
        ),
    ]
