# Generated by Django 3.2.5 on 2022-06-28 05:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0004_auto_20220628_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.CharField(max_length=500)),
                ('image1', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('image2', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('image3', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('image4', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.CharField(max_length=500)),
                ('spotlight_text1', models.CharField(max_length=500)),
                ('spotlight_text2', models.CharField(max_length=500)),
                ('spotlight_text3', models.CharField(max_length=500)),
                ('slider_image', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('info_image', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('education_image', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('research_image', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('innovation_image', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('mission_image', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('policies_image', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('plans_image', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='HomeImages',
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
