# Generated by Django 3.2.14 on 2022-09-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0005_technologyarea_technologyareadetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyareadetail',
            name='technology_abstract',
            field=models.TextField(null=True),
        ),
    ]
