# Generated by Django 3.2.5 on 2022-06-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0006_auto_20220628_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutData',
        ),
    ]
