# Generated by Django 3.2.14 on 2022-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0006_alter_technologyareadetail_technology_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyareadetail',
            name='institute',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='inventor_detail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='technology_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='technology_transferred',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
