# Generated by Django 3.2.14 on 2022-09-05 10:16

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0007_auto_20220901_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_title', models.CharField(max_length=200, null=True)),
                ('contributor_image', models.ImageField(max_length=200, upload_to='contributor_image')),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='headermenu',
            name='menu_link',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='institute',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='inventor_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='technology_abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='technology_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='technology_status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='technologyareadetail',
            name='technology_transferred',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
