# Generated by Django 3.2.5 on 2022-06-28 09:20

import django.core.files.storage
from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0007_delete_aboutdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text1', models.CharField(default='.', max_length=500)),
                ('about_text2', models.CharField(max_length=500)),
                ('about_text3', models.CharField(max_length=500)),
                ('about_text4', models.CharField(max_length=500)),
                ('about_text5', models.CharField(max_length=500)),
                ('about_text6', models.CharField(max_length=500)),
                ('image1', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('image2', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('image3', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('image4', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
    ]
