# Generated by Django 3.2.5 on 2022-06-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0008_aboutdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutData',
        ),
    ]
