# Generated by Django 3.2.14 on 2022-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0008_auto_20220905_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdata',
            name='about_image',
            field=models.ImageField(blank=True, upload_to='about_image'),
        ),
    ]
