# Generated by Django 3.2.14 on 2022-09-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0009_aboutdata_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdata',
            name='about_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
