# Generated by Django 3.2.14 on 2022-09-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0010_aboutdata_about_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutData',
        ),
    ]
