# Generated by Django 3.2.5 on 2022-06-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0010_aboutdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedata',
            name='info_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='spotlight_text1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='spotlight_text2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='homedata',
            name='spotlight_text3',
            field=models.TextField(null=True),
        ),
    ]
