# Generated by Django 3.2.5 on 2022-06-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0011_auto_20220629_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdata',
            name='about_text',
            field=models.TextField(null=True),
        ),
    ]
