# Generated by Django 3.2.14 on 2022-09-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0013_auto_20220927_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Central_Instrumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central_instrumentation_name', models.CharField(max_length=200, null=True)),
                ('institute_name', models.CharField(max_length=200, null=True)),
                ('district_name', models.CharField(max_length=200, null=True)),
                ('weblink', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CFC_Manufacturing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfc_name', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('weblink', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot_Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_title', models.CharField(max_length=200, null=True)),
                ('scale_detail', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('number', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
            ],
        ),
    ]
