# Generated by Django 3.2.14 on 2022-07-07 10:07

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0018_rename_info_text_homedata_home_info_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotlight_image', models.ImageField(blank=True, upload_to='spotlight_image')),
                ('spotlight_text', models.TextField(null=True)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='education_image',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='info_image',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='innovation_image',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='mission_image',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='plans_image',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='policies_image',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='research_image',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='slider_image',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='spotlight_text1',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='spotlight_text2',
        ),
        migrations.RemoveField(
            model_name='homedata',
            name='spotlight_text3',
        ),
        migrations.AddField(
            model_name='homedata',
            name='home_info_image',
            field=models.ImageField(blank=True, upload_to='home_info_image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(max_length=200, upload_to='banner_image'),
        ),
    ]
