# Generated by Django 3.2.14 on 2022-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0019_auto_20220707_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlight',
            name='spotlight_title',
            field=models.TextField(null=True),
        ),
    ]
