# Generated by Django 3.2.14 on 2022-07-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sti_app', '0020_spotlight_spotlight_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
